# generated by gen-stubs.py

import collections
import typing
from typing import Any

import libffrs

"""
FFRS - Fairly Fast & Flexible Reed-Solomon coding
"""

compiler_info: str
class CIRC16:
    """Cross-interleaved Reed-Solomon coding over :math:`GF(65537)`"""

    block_len: int
    """Total block length in number of elements"""

    block_size: int
    """Total block size in bytes"""

    ecc_len: int
    """Total ECC length in number of elements"""

    ecc_size: int
    """Total ECC size in bytes"""

    inner_block_len: int
    """Inner codec block length in number of elements"""

    inner_block_size: int
    """Inner codec block size in bytes"""

    inner_ecc_len: int
    """Inner codec ECC length in number of elements"""

    inner_ecc_size: int
    """Inner codec ECC size in bytes"""

    inner_message_len: int
    """Inner codec message length in number of elements"""

    inner_message_size: int
    """Inner codec message size in bytes"""

    interleave: int
    """Number of interleaved CIRC blocks"""

    message_len: int
    """Total message length in number of elements"""

    message_size: int
    """Total message size in bytes"""

    outer_block_len: int
    """Outer codec block length in number of elements"""

    outer_ecc_len: int
    """Outer codec ECC length in number of elements"""

    outer_interleave: int
    """Outer codec interleaving (``inner_message_len * interleave``)"""

    outer_message_len: int
    """Outer codec message length in number of elements"""

    primitive: int
    """Primitive value used to generate the Galois field"""

    rsi: libffrs.RSi16
    """Inner Reed-Solomon codec (:class:`RSi16`)"""

    rso: libffrs.RSi16
    """Outer Reed-Solomon codec (:class:`RSi16`)"""

    simd_x16: bool
    """SIMD x16 encoding enabled (AVX512)"""

    simd_x4: bool
    """SIMD x4 encoding enabled (SSE2)"""

    simd_x8: bool
    """SIMD x8 encoding enabled (AVX2)"""

    def __init__(self: libffrs.CIRC16, inner_block_len: typing.SupportsInt | typing.SupportsIndex, inner_ecc_len: typing.SupportsInt | typing.SupportsIndex, outer_block_len: typing.SupportsInt | typing.SupportsIndex, outer_ecc_len: typing.SupportsInt | typing.SupportsIndex, interleave: typing.SupportsInt | typing.SupportsIndex = 1, *, primitive: typing.SupportsInt | typing.SupportsIndex = 3, simd_x4: bool | None = None, simd_x8: bool | None = None, simd_x16: bool | None = None) -> None:
        ...
    def encode(self: libffrs.CIRC16, buffer: collections.abc.Buffer) -> bytearray:
        ...
    def repair(self: libffrs.CIRC16, message: collections.abc.Buffer, ecc: collections.abc.Buffer) -> bool:
        ...


class GF256:
    """Finite-field operations optimized for :math:`GF(2^8)`"""

    field_elements: int
    """Always 256"""

    poly1: int
    """Masked irreducible polynomial, excluding MSb"""

    power: int
    """Always 8"""

    prime: int
    """Always 2"""

    primitive: int
    """Primitive value used to generate the field"""

    def __init__(self: libffrs.GF256, primitive: typing.SupportsInt | typing.SupportsIndex = 2, poly1: typing.SupportsInt | typing.SupportsIndex = 285) -> None:
        ...
    def add(self: libffrs.GF256, lhs: typing.SupportsInt | typing.SupportsIndex, rhs: typing.SupportsInt | typing.SupportsIndex) -> int:
        ...
    def div(self: libffrs.GF256, num: typing.SupportsInt | typing.SupportsIndex, den: typing.SupportsInt | typing.SupportsIndex) -> int:
        ...
    def exp(self: libffrs.GF256, value: typing.SupportsInt | typing.SupportsIndex) -> int:
        ...
    def inv(self: libffrs.GF256, value: typing.SupportsInt | typing.SupportsIndex) -> int:
        ...
    def log(self: libffrs.GF256, value: typing.SupportsInt | typing.SupportsIndex) -> int:
        ...
    def mul(self: libffrs.GF256, lhs: typing.SupportsInt | typing.SupportsIndex, rhs: typing.SupportsInt | typing.SupportsIndex) -> int:
        ...
    def mul8(self: libffrs.GF256, a: collections.abc.Buffer, b: collections.abc.Buffer) -> bytearray:
        ...
    def poly_add(self: libffrs.GF256, p1: collections.abc.Buffer, p2: collections.abc.Buffer) -> bytearray:
        ...
    def poly_divmod(self: libffrs.GF256, p1: collections.abc.Buffer, p2: collections.abc.Buffer) -> tuple:
        ...
    def poly_eval(self: libffrs.GF256, poly: collections.abc.Buffer, x: typing.SupportsInt | typing.SupportsIndex) -> int:
        ...
    def poly_eval8(self: libffrs.GF256, poly: collections.abc.Buffer, xs: collections.abc.Buffer) -> bytearray:
        ...
    def poly_mod(self: libffrs.GF256, p1: collections.abc.Buffer, p2: collections.abc.Buffer) -> bytearray:
        ...
    def poly_mod_x_n(self: libffrs.GF256, p1: collections.abc.Buffer, p2: collections.abc.Buffer) -> bytearray:
        ...
    def poly_mul(self: libffrs.GF256, p1: collections.abc.Buffer, p2: collections.abc.Buffer) -> bytearray:
        ...
    def poly_sub(self: libffrs.GF256, p1: collections.abc.Buffer, p2: collections.abc.Buffer) -> bytearray:
        ...
    def pow(self: libffrs.GF256, base: typing.SupportsInt | typing.SupportsIndex, exponent: typing.SupportsInt | typing.SupportsIndex) -> int:
        ...
    def sub(self: libffrs.GF256, lhs: typing.SupportsInt | typing.SupportsIndex, rhs: typing.SupportsInt | typing.SupportsIndex) -> int:
        ...


class GFi16:
    """Finite-field operations over :math:`GF(65537)`"""

    field_elements: int
    """:math:`p`"""

    power: int
    """Always 1"""

    prime: int
    """:math:`p`"""

    primitive: int
    """Primitive value used to generate the field"""

    def __init__(self: libffrs.GFi16, primitive: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def add(self: libffrs.GFi16, lhs: typing.SupportsInt | typing.SupportsIndex, rhs: typing.SupportsInt | typing.SupportsIndex) -> int:
        ...
    def div(self: libffrs.GFi16, num: typing.SupportsInt | typing.SupportsIndex, den: typing.SupportsInt | typing.SupportsIndex) -> int:
        ...
    def exp(self: libffrs.GFi16, value: typing.SupportsInt | typing.SupportsIndex) -> int:
        ...
    def inv(self: libffrs.GFi16, value: typing.SupportsInt | typing.SupportsIndex) -> int:
        ...
    def log(self: libffrs.GFi16, value: typing.SupportsInt | typing.SupportsIndex) -> int:
        ...
    def mul(self: libffrs.GFi16, lhs: typing.SupportsInt | typing.SupportsIndex, rhs: typing.SupportsInt | typing.SupportsIndex) -> int:
        ...
    def pow(self: libffrs.GFi16, base: typing.SupportsInt | typing.SupportsIndex, exponent: typing.SupportsInt | typing.SupportsIndex) -> int:
        ...
    def sub(self: libffrs.GFi16, lhs: typing.SupportsInt | typing.SupportsIndex, rhs: typing.SupportsInt | typing.SupportsIndex) -> int:
        ...


class RS256:
    """Reed-Solomon coding over :math:`GF(2^8)`"""

    block_len: int
    block_size: int
    ecc_len: int
    ecc_size: int
    generator: bytes
    generator_roots: bytes
    gf: libffrs.GF256
    message_len: int
    message_size: int
    def __init__(self: libffrs.RS256, block_len: typing.SupportsInt | typing.SupportsIndex | None = None, message_len: typing.SupportsInt | typing.SupportsIndex | None = None, ecc_len: typing.SupportsInt | typing.SupportsIndex | None = None, primitive: typing.SupportsInt | typing.SupportsIndex = 2, polynomial: typing.SupportsInt | typing.SupportsIndex = 285) -> None:
        ...
    def _synds(self: libffrs.RS256, buffer: collections.abc.Buffer) -> bytearray:
        ...
    def encode(self: libffrs.RS256, buffer: collections.abc.Buffer) -> bytearray:
        ...
    def repair(self: libffrs.RS256, buffer: collections.abc.Buffer, ecc: collections.abc.Buffer) -> bool:
        ...


class RSi16:
    """Reed-Solomon coding over :math:`GF(65537)`"""

    block_len: int
    """Interleaved block length in number of elements"""

    block_size: int
    """Interleaved block size in bytes"""

    ecc_len: int
    """Interleaved error correction code length in number of elements"""

    ecc_size: int
    """Interleaved error correction code size in bytes"""

    gf: libffrs.GFi16
    """:class:`GFi16` instance for :math:`GF(65537)`"""

    interleave: int
    """Number of interleaved columns"""

    message_len: int
    """Interleaved message length in number of elements"""

    message_size: int
    """Interleaved message size in bytes"""

    ntt_len: int
    """Number theoretic transform length"""

    ntt_size: int
    """Number theoretic transform size in bytes"""

    root: int
    """:math:`n`-th root of unity used by NTT"""

    rs_block_len: int
    """Reed-Solomon block length in number of elements"""

    rs_block_size: int
    """Reed-Solomon block size in bytes"""

    rs_ecc_len: int
    """Reed-Solomon error correction code length in number of elements"""

    rs_ecc_size: int
    """Reed-Solomon error correction code size in bytes"""

    rs_message_len: int
    """Reed-Solomon message length in number of elements"""

    rs_message_size: int
    """Reed-Solomon message size in bytes"""

    simd_x16: bool
    """SIMD x16 encoding enabled (AVX512)"""

    simd_x4: bool
    """SIMD x4 encoding enabled (SSE2)"""

    simd_x8: bool
    """SIMD x8 encoding enabled (AVX2)"""

    def __init__(self: libffrs.RSi16, block_len: typing.SupportsInt | typing.SupportsIndex, ecc_len: typing.SupportsInt | typing.SupportsIndex, interleave: typing.SupportsInt | typing.SupportsIndex = 1, *, primitive: typing.SupportsInt | typing.SupportsIndex = 3, simd_x4: bool | None = None, simd_x8: bool | None = None, simd_x16: bool | None = None) -> None:
        ...
    def encode(self: libffrs.RSi16, buffer: collections.abc.Buffer) -> bytearray:
        ...
    def rbo(self: libffrs.RSi16, i: typing.SupportsInt | typing.SupportsIndex) -> int:
        ...
    def repair(self: libffrs.RSi16, message: collections.abc.Buffer, ecc: collections.abc.Buffer, error_pos: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex] | None = None) -> None:
        ...
    def synd(self: libffrs.RSi16, message: collections.abc.Buffer, ecc: collections.abc.Buffer) -> bytearray:
        ...


def create_buffer(size: typing.SupportsInt | typing.SupportsIndex) -> memoryview:
    ...
def set_logger(logger: object) -> None:
    ...
