# generated by gen-stubs.py

import collections
import typing
from typing import Any

import libffrs

"""
FFRS main module
"""

compiler_info: str
class CIRC16:
    block_len: int
    block_size: int
    ecc_len: int
    ecc_size: int
    inner_block_len: int
    inner_block_size: int
    inner_ecc_len: int
    inner_ecc_size: int
    inner_message_len: int
    inner_message_size: int
    interleave: int
    message_len: int
    message_size: int
    outer_block_len: int
    outer_ecc_len: int
    outer_message_len: int
    rsi: libffrs.RSi16
    rso: libffrs.RSi16
    def __init__(self: libffrs.CIRC16, inner_block_len: typing.SupportsInt | typing.SupportsIndex, inner_ecc_len: typing.SupportsInt | typing.SupportsIndex, outer_block_len: typing.SupportsInt | typing.SupportsIndex, outer_ecc_len: typing.SupportsInt | typing.SupportsIndex, interleave: typing.SupportsInt | typing.SupportsIndex = 1, *, primitive: typing.SupportsInt | typing.SupportsIndex = 3, simd_x4: bool | None = None, simd_x8: bool | None = None, simd_x16: bool | None = None) -> None:
        ...
    def encode(self: libffrs.CIRC16, buffer: collections.abc.Buffer) -> bytearray:
        ...
    def repair(self: libffrs.CIRC16, message: collections.abc.Buffer, ecc: collections.abc.Buffer) -> bool:
        ...


class GF256:
    """Finite-field operations optimized for :math:`GF(2^8)`"""

    field_elements: int
    """Always 256"""

    poly1: int
    """Masked irreducible polynomial, excluding MSb"""

    power: int
    """Always 8"""

    prime: int
    """Always 2"""

    primitive: int
    """Primitive value used to generate the field"""

    def __init__(self: libffrs.GF256, primitive: typing.SupportsInt | typing.SupportsIndex = 2, poly1: typing.SupportsInt | typing.SupportsIndex = 285) -> None:
        ...
    def add(self: libffrs.GF256, lhs: typing.SupportsInt | typing.SupportsIndex, rhs: typing.SupportsInt | typing.SupportsIndex) -> int:
        ...
    def div(self: libffrs.GF256, num: typing.SupportsInt | typing.SupportsIndex, den: typing.SupportsInt | typing.SupportsIndex) -> int:
        ...
    def exp(self: libffrs.GF256, value: typing.SupportsInt | typing.SupportsIndex) -> int:
        ...
    def inv(self: libffrs.GF256, value: typing.SupportsInt | typing.SupportsIndex) -> int:
        ...
    def log(self: libffrs.GF256, value: typing.SupportsInt | typing.SupportsIndex) -> int:
        ...
    def mul(self: libffrs.GF256, lhs: typing.SupportsInt | typing.SupportsIndex, rhs: typing.SupportsInt | typing.SupportsIndex) -> int:
        ...
    def mul8(self: libffrs.GF256, a: collections.abc.Buffer, b: collections.abc.Buffer) -> bytearray:
        ...
    def poly_add(self: libffrs.GF256, p1: collections.abc.Buffer, p2: collections.abc.Buffer) -> bytearray:
        ...
    def poly_divmod(self: libffrs.GF256, p1: collections.abc.Buffer, p2: collections.abc.Buffer) -> tuple:
        ...
    def poly_eval(self: libffrs.GF256, poly: collections.abc.Buffer, x: typing.SupportsInt | typing.SupportsIndex) -> int:
        ...
    def poly_eval8(self: libffrs.GF256, poly: collections.abc.Buffer, xs: collections.abc.Buffer) -> bytearray:
        ...
    def poly_mod(self: libffrs.GF256, p1: collections.abc.Buffer, p2: collections.abc.Buffer) -> bytearray:
        ...
    def poly_mod_x_n(self: libffrs.GF256, p1: collections.abc.Buffer, p2: collections.abc.Buffer) -> bytearray:
        ...
    def poly_mul(self: libffrs.GF256, p1: collections.abc.Buffer, p2: collections.abc.Buffer) -> bytearray:
        ...
    def poly_sub(self: libffrs.GF256, p1: collections.abc.Buffer, p2: collections.abc.Buffer) -> bytearray:
        ...
    def pow(self: libffrs.GF256, base: typing.SupportsInt | typing.SupportsIndex, exponent: typing.SupportsInt | typing.SupportsIndex) -> int:
        ...
    def sub(self: libffrs.GF256, lhs: typing.SupportsInt | typing.SupportsIndex, rhs: typing.SupportsInt | typing.SupportsIndex) -> int:
        ...


class GFi16:
    """Finite-field operations for prime fields <= 65537"""

    field_elements: int
    """:math:`p`"""

    power: int
    """Always 1"""

    prime: int
    """:math:`p`"""

    primitive: int
    """Primitive value used to generate the field"""

    def __init__(self: libffrs.GFi16, primitive: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def add(self: libffrs.GFi16, lhs: typing.SupportsInt | typing.SupportsIndex, rhs: typing.SupportsInt | typing.SupportsIndex) -> int:
        ...
    def div(self: libffrs.GFi16, num: typing.SupportsInt | typing.SupportsIndex, den: typing.SupportsInt | typing.SupportsIndex) -> int:
        ...
    def exp(self: libffrs.GFi16, value: typing.SupportsInt | typing.SupportsIndex) -> int:
        ...
    def inv(self: libffrs.GFi16, value: typing.SupportsInt | typing.SupportsIndex) -> int:
        ...
    def log(self: libffrs.GFi16, value: typing.SupportsInt | typing.SupportsIndex) -> int:
        ...
    def mul(self: libffrs.GFi16, lhs: typing.SupportsInt | typing.SupportsIndex, rhs: typing.SupportsInt | typing.SupportsIndex) -> int:
        ...
    def pow(self: libffrs.GFi16, base: typing.SupportsInt | typing.SupportsIndex, exponent: typing.SupportsInt | typing.SupportsIndex) -> int:
        ...
    def sub(self: libffrs.GFi16, lhs: typing.SupportsInt | typing.SupportsIndex, rhs: typing.SupportsInt | typing.SupportsIndex) -> int:
        ...


class RS256:
    """Reed-Solomon coding over :math:`GF(2^8)`"""

    block_len: int
    block_size: int
    ecc_len: int
    ecc_size: int
    generator: bytes
    generator_roots: bytes
    gf: libffrs.GF256
    message_len: int
    message_size: int
    def __init__(self: libffrs.RS256, block_len: typing.SupportsInt | typing.SupportsIndex | None = None, message_len: typing.SupportsInt | typing.SupportsIndex | None = None, ecc_len: typing.SupportsInt | typing.SupportsIndex | None = None, primitive: typing.SupportsInt | typing.SupportsIndex = 2, polynomial: typing.SupportsInt | typing.SupportsIndex = 285) -> None:
        ...
    def _synds(self: libffrs.RS256, buffer: collections.abc.Buffer) -> bytearray:
        ...
    def encode(self: libffrs.RS256, buffer: collections.abc.Buffer) -> bytearray:
        ...
    def repair(self: libffrs.RS256, buffer: collections.abc.Buffer, ecc: collections.abc.Buffer) -> bool:
        ...


class RSi16:
    """Reed-Solomon coding over :math:`GF(65537)`"""

    block_len: int
    block_size: int
    ecc_len: int
    ecc_size: int
    gf: libffrs.GFi16
    interleave: int
    """Number of interleaved codewords for block encoding"""

    message_len: int
    message_size: int
    ntt_len: int
    ntt_size: int
    root: int
    rs_block_len: int
    rs_block_size: int
    rs_ecc_len: int
    rs_ecc_size: int
    rs_message_len: int
    rs_message_size: int
    simd_x16: bool
    """Enable SIMD x16 encoding"""

    simd_x4: bool
    """Enable SIMD x4 encoding"""

    simd_x8: bool
    """Enable SIMD x8 encoding"""

    def __init__(self: libffrs.RSi16, block_len: typing.SupportsInt | typing.SupportsIndex, ecc_len: typing.SupportsInt | typing.SupportsIndex, interleave: typing.SupportsInt | typing.SupportsIndex = 1, *, primitive: typing.SupportsInt | typing.SupportsIndex = 3, simd_x4: bool | None = None, simd_x8: bool | None = None, simd_x16: bool | None = None) -> None:
        ...
    def encode(self: libffrs.RSi16, buffer: collections.abc.Buffer) -> bytearray:
        ...
    def rbo(self: libffrs.RSi16, i: typing.SupportsInt | typing.SupportsIndex) -> int:
        ...
    def repair(self: libffrs.RSi16, message: collections.abc.Buffer, ecc: collections.abc.Buffer, error_pos: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex] | None = None) -> None:
        ...
    def synd(self: libffrs.RSi16, message: collections.abc.Buffer, ecc: collections.abc.Buffer) -> bytearray:
        ...


def create_buffer(arg0: typing.SupportsInt | typing.SupportsIndex) -> memoryview:
    ...
