import inspect
import sys
import textwrap

import libffrs


def format_docstring(txt: str) -> str:
    txt = textwrap.dedent(txt).strip()
    docstring = '"""'
    if txt.count("\n"):
        docstring += "\n"
        docstring += txt
        docstring += "\n"
    else:
        docstring += txt
    docstring += '"""\n'
    return docstring


def fullname(cls):
    module = cls.__module__
    if module == "builtins":
        return cls.__qualname__
    return f"{module}.{cls.__qualname__}"


def gen(obj, instances) -> str:
    is_class = inspect.isclass(obj)

    if not is_class and not inspect.ismodule(obj):
        cls = obj.__class__
    else:
        cls = obj

    lines = []

    filtered_members = list(
        filter(
            lambda x: not ((x[0].startswith("__") and x[0] != "__init__") or x[0].startswith("_pybind11")),
            inspect.getmembers(cls),
        )
    )

    # Attributes
    for name, member in filtered_members:
        if not callable(member):
            type_ = "Any" if is_class else fullname(getattr(obj, name).__class__)
            lines.append(f"{name}: {type_}")
            if isinstance(member, property) and member.__doc__:
                lines.append(format_docstring(member.__doc__))

    # Classes
    for name, member in filtered_members:
        if inspect.isclass(member):
            cls_lines = [f"class {name}:"]

            if member.__doc__:
                cls_lines.append(textwrap.indent(format_docstring(member.__doc__), "    "))

            member = instances.get(name, member)
            attrs = gen(member, instances)
            if attrs:
                cls_lines.append(textwrap.indent(attrs, "    "))
            else:
                cls_lines.append("    ...\n")

            cls_lines.append("\n")
            lines.append("\n".join(cls_lines))

    # Methods
    for name, member in filtered_members:
        if not inspect.isclass(member) and callable(member):
            newline = member.__doc__.find("\n")
            sig = member.__doc__[:newline]
            if sig.startswith(name):
                doc = member.__doc__[newline + 1 :].strip()

                method_body = ""
                if doc:
                    method_body += textwrap.indent(format_docstring(doc), "    ")
                else:
                    method_body += "    ..."
                lines.append(f"def {sig}:\n{method_body}")
            else:
                lines.append(f"def {name}(self, *args, **kwargs) -> Any: ...\n")

    return "\n".join(lines)


header = """\
# generated by gen-stubs.py

import collections
import typing
from typing import Any

import libffrs

"""

class_stubs = {
    "RSi16": libffrs.RSi16(4, 2),
    "CIRC16": libffrs.CIRC16(4, 2, 4, 2),
    "GFi16": libffrs.GFi16(3),
    "GF256": libffrs.GF256(),
    "RS256": libffrs.RS256(4, 2),
    "NTT": libffrs.RSi16(4, 2).ntt,
    "RepairStatus": libffrs.RepairStatus(0),
}

output_dir = sys.argv[1]

with open(output_dir + "/__init__.pyi", "w", encoding="utf8") as f:
    f.write(header)
    if libffrs.__doc__:
        f.write(f'"""\n{textwrap.dedent(libffrs.__doc__).strip()}\n"""\n\n')

    f.write(gen(libffrs, class_stubs))
    f.write("\n")
