import inspect
import os
import sys
import textwrap

import libffrs


def format_docstring(txt: str) -> str:
    txt = textwrap.dedent(txt).strip()
    docstring = '"""'
    if txt.count("\n"):
        docstring += "\n"
        docstring += txt
        docstring += "\n"
    else:
        docstring += txt
    docstring += '"""'
    return docstring


def generate_stub(cls, overrides=None, property_types=None) -> str:
    overrides = overrides or {}
    property_types = property_types or {}
    class_name = cls.__name__

    lines = [f"class {class_name}:"]

    members = inspect.getmembers(cls)
    count = False

    for name, member in members:
        if name.startswith("__") or name.startswith("_pybind11"):
            continue

        elif callable(member):
            assert member.__doc__
            newline = member.__doc__.find("\n")
            sig = member.__doc__[:newline]
            doc = member.__doc__[newline + 1 :].strip()

            method_body = textwrap.indent(format_docstring(doc), "    ")
            method_body += "\n    ..."
            lines.append(textwrap.indent(f"def {sig}:\n{method_body}", "    "))

        else:  # attribute
            type_ = property_types.get(name, "Any")
            if name.endswith("_len") or name.endswith("_size"):
                type_ = "int"
            if name.startswith("simd_x"):
                type_ = "bool"

            lines.append(f"    {name}: {type_}")

            if member.__doc__:
                lines.append(textwrap.indent(format_docstring(member.__doc__), "    "))

        count += 1

    if not count:
        lines.append("    pass")

    return "\n".join(lines)


header = """\
# generated by gen-stubs.py

import collections
import typing
from typing import Any

import libffrs

"""

class_stubs = {
    "RSi16md": {"cls": libffrs.RSi16md, "property_types": dict(root="int", interleave="int", gf="libffrs.GFi16")},
}
for cls in dir(libffrs):
    if cls.startswith("_") or not inspect.isclass(getattr(libffrs, cls)) or cls in class_stubs:
        continue
    class_stubs[cls] = {"cls": getattr(libffrs, cls)}


output_dir = sys.argv[1]

with open(output_dir + "/__init__.pyi", "w", encoding="utf8") as f:
    f.write(header)
    if libffrs.__doc__:
        f.write(f'"""\n{textwrap.dedent(libffrs.__doc__).strip()}\n"""\n')
    for stub in class_stubs.values():
        f.write("\n\n")
        f.write(generate_stub(**stub))
        f.write("\n")
