# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

import os
import pathlib

def rst_exists(path):
    return pathlib.Path(path).exists()


project = "libffrs"
copyright = "2026, Gabriel Machado"
author = "Gabriel Machado"

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.intersphinx",
    "sphinx.ext.autosummary",
    "sphinx.ext.napoleon",
    # 'sphinx.ext.linkcode',
]

templates_path = ["_templates"]
exclude_patterns = [
    "generated/ffrs.reference.*",
]


# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = "furo"
html_static_path = ["_static"]
html_css_files = [
    "css/custom.css",
]


# syntax highlighting
pygments_style = "sphinx"

# -- Options for extensions --------------------------------------------------

autosummary_generate = True
autosummary_ignore_module_all = False
autosummary_context = {
    "exists": os.path.exists,
}

# Suppress warning generated by the presence of a `exists` in the context
suppress_warnings = ["config.cache"]
