# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

import os
import pathlib
import shlex
import subprocess
import sys
import textwrap

from docutils import nodes
from docutils.parsers.rst import Directive
from docutils.statemachine import StringList

import ffrs.par.cli


def rst_exists(path):
    return pathlib.Path(path).exists()


project = "libffrs"
copyright = "2026, Gabriel Machado"
author = "Gabriel Machado"

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.intersphinx",
    "sphinx.ext.autosummary",
    "sphinx.ext.napoleon",
    "docs.argparse_directive",
    # 'sphinx.ext.linkcode',
]

templates_path = ["_templates"]
exclude_patterns = [
    "generated/ffrs.reference.*",
]


# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = "furo"
html_static_path = ["_static"]
html_css_files = [
    "css/custom.css",
]


# syntax highlighting
pygments_style = "sphinx"

# -- Options for extensions --------------------------------------------------

autosummary_generate = True
autosummary_ignore_module_all = False
autosummary_context = {
    "exists": os.path.exists,
}

# Suppress warning generated by the presence of a `exists` in the context
suppress_warnings = ["config.cache"]


class Runner(Directive):
    final_argument_whitespace = True
    has_content = False
    required_arguments = 1

    def run(self):
        args = shlex.split(self.arguments[0])

        result = subprocess.run(
            [sys.executable, "-m", *args],
            capture_output=True,
            text=True,
        )
        text = result.stdout.strip() if result.stdout else result.stderr.strip()
        # text = textwrap.indent(text, "    ")

        return [nodes.literal_block(text, text, language="console")]

        container = nodes.container(classes=["monospace"])
        self.state.nested_parse(
            StringList(text.splitlines()),
            self.content_offset,
            container,
        )
        return [container]


def setup(app):
    app.add_directive("run-cli", Runner)
